# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff70ad881e7b59931963b01bd37bbbde228165611ff6cd1a85ff6f963a74c21d06b8e24ae84cf31d991a00928301bfffcabcf4737af9cdb49fd8f3acc616eb17

test:
  secret_key_base: f5167df87698f4c1e4e65e62a4bfffe1feef5f70fc7d0fd5d0110597290bffb2b5e7cf5d88ffe1ee57782f7dcf9f721ed4314c68ec84222935eaf488ec3d2ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
