# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: 8e72cd06c45aecb37f1f196cb795a4d6c5d148ccabfd5cbb54004f1bf10e29c1ffb28b5a771a1ecd582848447d7e358288328997c714080a641a41cbe954be05
  twitter_api_key: BQYtrvmCn1WVX2lFWE9bPrbBA
  twitter_api_secret: Et6zbOmlYGfdQZtHBxdcxgydtOhEQUUyhe9UV2TaMW1Jmevd0k
  facebook_api_key: 245866608939582
  facebook_api_secret: 63712ed52cb3c90d109ef51785484040

test:
  secret_key_base: c804d15faee1c9e823f00a205ca9340941801a27073afda1fd77c63b22e1b65884c5c3871326aa90508e626a4bd2a198a4a12150ad0536e7417857847592d4cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
